"""Configuration package for Sumo Digital Twin."""
from config.config import (
    SensorSpec,
    RobotClassConfig,
    KIT_1KG_CONFIG,
    MEGA_3KG_CONFIG,
    CONFIG_REGISTRY,
    PROJECT_ROOT,
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    AGENT_DATA_DIR,
    OBSERVER_DATA_DIR,
    DT_DATA_DIR,
    SIMULATION_DT_S,
    COULOMB_FRICTION_MU,
    DEFAULT_MATCH_MAX_TICKS,
    SPECULAR_MAX_ANGLE_DEG,
    EDGE_LINE_THRESHOLD,
)

__all__ = [
    "SensorSpec",
    "RobotClassConfig",
    "KIT_1KG_CONFIG",
    "MEGA_3KG_CONFIG",
    "CONFIG_REGISTRY",
    "PROJECT_ROOT",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "AGENT_DATA_DIR",
    "OBSERVER_DATA_DIR",
    "DT_DATA_DIR",
    "SIMULATION_DT_S",
    "COULOMB_FRICTION_MU",
    "DEFAULT_MATCH_MAX_TICKS",
    "SPECULAR_MAX_ANGLE_DEG",
    "EDGE_LINE_THRESHOLD",
]
